void circle_par(double p[3], double t);
int circle_int(double solOb[3], double p1[3], double p2[3]);
int circle_norm(double norm[3], double p[3]); 
void plane_par(double p[3], double u, double v);
int plane_int(double solOb[3], double p1[3], double p2[3]);
int plane_norm(double norm[3], double p[3]);
void sphere_par1(double p[3], double u, double v);
void sphere_par2(double p[3], double u, double v);
int sphere_int(double solOb[3], double p1[3], double p2[3]);
int sphere_norm(double norm[3], double p[3]);
void hyper_par(double p[3], double u, double v);
int hyper_int(double solOb[3], double p1[2], double p2[3]);
int hyper_norm(double norm[3], double p[3]); 
