
1.  what is a vector?    arrow, translation
    <3,4> versus (3,4)
    alternate notation, 3i + 4j

2.  how to find the vector between two points P1, P2 ?

3.  m*A,  A + B,  A - B,  |A|,  A_u = A/|A|

4.  vectors in space

5.  Suppose we need the angle between two vectors :

    dot product, A.B = Ax*Bx + Ay*By + Az*Bz (definition)
                     = |A| |B| cos(t) (theorem)

    A.B = 0 iff A perpendicular B  (provided A and B not zero)

6.  Sometimes we will need to find a new vector that is
    perpendicular to the plane generated by two known vectors :

    cross product, C = AxB = < (Ay*Bz - Az*By),
                              -(Ax*Bz - Az*Bx),
                               (Ax*By - Ay*Bx) >

    determinant memory aid :
    i  j  k
    Ax Ay Az
    Bx By Bz

    verify that A.C= 0 and B.C = 0

7.  Note that A.B = B.A  but  AxB = -BxA


                          
                          

